# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='users',
            field=models.ManyToManyField(related_name='ints', to='mtm_app.User'),
        ),
    ]
