# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtm_app', '0002_auto_20170222_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='interests', to='mtm_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='interests',
            name='users',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
