# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtm_app', '0003_auto_20170222_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
